#!/bin/bash
# set -e

for packageDir in packages/* ; do
    for sub in "$packageDir"/** ; do
        if [[ !($sub == *.json ||  $sub == *.md) ]]
        then
            rm -rf $sub
        fi
    done
done

rm -rf ./src/*/tsBuild.info
rm -rf test/{dist,tsBuild.info,public/web_modules}
