#!/bin/bash
set -e

tsconfig=$(<tasks/config/tsconfig.json)
for srcDirectory in src/* ; do
	dirName=$( basename $srcDirectory)
  # if [ "$dirName" != "testing" ]
  # then
    contet="${tsconfig/package_name/$dirName}"
    echo "$contet" > "$srcDirectory/tsconfig.json"
  # fi
done

cp tasks/config/tsconfig.compilerOption.json packages/core
